In [1]:
import numpy as np
import pandas as pd

# Create the training dataset
data = pd.DataFrame({
    'X1': [0, 2, 0, 0, -1, 1],
    'X2': [3, 0, 1, 1, 0, 1],
    'X3': [0, 0, 3, 2, 1, 1],
    'Y': ['Red', 'Red', 'Red', 'Green', 'Green', 'Red']
})

data

   X1  X2  X3      Y
0   0   3   0    Red
1   2   0   0    Red
2   0   1   3    Red
3   0   1   2  Green
4  -1   0   1  Green
5   1   1   1    Red

In [2]:
# Test point
test_point = np.array([0, 0, 0])

In [3]:
# Function to calculate Euclidean distance
def euclidean_distance(row, test_point):
    point = np.array([row['X1'], row['X2'], row['X3']])
    return np.sqrt(np.sum((point - test_point) ** 2))

# Calculate distances for each observation
data['Distance'] = data.apply(lambda row: euclidean_distance(row, test_point), axis=1)

In [4]:
data

   X1  X2  X3      Y  Distance
0   0   3   0    Red  3.000000
1   2   0   0    Red  2.000000
2   0   1   3    Red  3.162278
3   0   1   2  Green  2.236068
4  -1   0   1  Green  1.414214
5   1   1   1    Red  1.732051

In [5]:
# Sort by distance and add observation number
data['Observation'] = range(1, len(data) + 1)

In [6]:
data

   X1  X2  X3      Y  Distance  Observation
0   0   3   0    Red  3.000000            1
1   2   0   0    Red  2.000000            2
2   0   1   3    Red  3.162278            3
3   0   1   2  Green  2.236068            4
4  -1   0   1  Green  1.414214            5
5   1   1   1    Red  1.732051            6

In [8]:
result = data.sort_values('Distance')
result

   X1  X2  X3      Y  Distance  Observation
4  -1   0   1  Green  1.414214            5
5   1   1   1    Red  1.732051            6
1   2   0   0    Red  2.000000            2
3   0   1   2  Green  2.236068            4
0   0   3   0    Red  3.000000            1
2   0   1   3    Red  3.162278            3

In [9]:
# Print results
print("\nEuclidean Distances from test point (0,0,0):")
print("=" * 60)
print("Obs  X1  X2  X3    Y     Distance")
print("-" * 60)
for idx, row in result.iterrows():
    print(f"{int(row['Observation']):2d}   {row['X1']:2.0f}   {row['X2']:2.0f}   {row['X3']:2.0f}   {row['Y']:<6} {row['Distance']:8.3f}")
print("=" * 60)

# Print ordered distances
print("\nOrdered from nearest to farthest:")
print("-" * 60)
for idx, row in result.iterrows():
    print(f"Observation {int(row['Observation'])}: distance = {row['Distance']:.3f} ({row['Y']})")

Euclidean Distances from test point (0,0,0):
============================================================
Obs  X1  X2  X3    Y     Distance
------------------------------------------------------------
 5   -1    0    1   Green     1.414
 6    1    1    1   Red       1.732
 2    2    0    0   Red       2.000
 4    0    1    2   Green     2.236
 1    0    3    0   Red       3.000
 3    0    1    3   Red       3.162
============================================================

Ordered from nearest to farthest:
------------------------------------------------------------
Observation 5: distance = 1.414 (Green)
Observation 6: distance = 1.732 (Red)
Observation 2: distance = 2.000 (Red)
Observation 4: distance = 2.236 (Green)
Observation 1: distance = 3.000 (Red)
Observation 3: distance = 3.162 (Red)