# Dealing With Missing Values

In [1]:
import pandas as pd
import numpy as np
import statsmodels.formula.api as smf

In [2]:
# Load and prepare the dataset (using a small dataset for demonstration)
data = {
 'Income':[56, 58, 60, 62, np.nan, 69, 73, 75],
 'Age':[22, 23, np.nan, 25, 27, 33, 36, 38],
 'Edu':[11, 13, np.nan, 14 , 15, 16, 18, 20]
}

In [3]:
data

{'Income': [56, 58, 60, 62, nan, 69, 73, 75],
 'Age': [22, 23, nan, 25, 27, 33, 36, 38],
 'Edu': [11, 13, nan, 14, 15, 16, 18, 20]}

In [4]:
df = pd.DataFrame(data)

In [5]:
df

   Income   Age   Edu
0    56.0  22.0  11.0
1    58.0  23.0  13.0
2    60.0   NaN   NaN
3    62.0  25.0  14.0
4     NaN  27.0  15.0
5    69.0  33.0  16.0
6    73.0  36.0  18.0
7    75.0  38.0  20.0

In [6]:
# Detect missing values
missing_values = df.isnull()
print("Missing Values:\n", missing_values)

Missing Values:
    Income    Age    Edu
0   False  False  False
1   False  False  False
2   False   True   True
3   False  False  False
4    True  False  False
5   False  False  False
6   False  False  False
7   False  False  False

In [7]:
# Detect missing values
print("Missing values in each column:")
print(df.isnull().sum())

Missing values in each column:
Income    1
Age       1
Edu       1
dtype: int64

In [8]:
# Percentage of missing values in each column:
missing_percentage = (df.isnull().sum() / len(df)) * 100
print("Percentage of missing values in each column:")
print(missing_percentage[missing_percentage > 0])

Percentage of missing values in each column:
Income    12.5
Age       12.5
Edu       12.5
dtype: float64

In [9]:
df_filled = df.fillna(0)

In [10]:
print("\nDataFrame after replacing missing values with 0:")
print(df_filled)

DataFrame after replacing missing values with 0:
   Income   Age   Edu
0    56.0  22.0  11.0
1    58.0  23.0  13.0
2    60.0   0.0   0.0
3    62.0  25.0  14.0
4     0.0  27.0  15.0
5    69.0  33.0  16.0
6    73.0  36.0  18.0
7    75.0  38.0  20.0

In [11]:
# Replace missing values with the mean of each column
df_mean_filled = df.fillna(df.mean())
print("\nDataFrame after replacing missing values with column means:")
print(df_mean_filled)

DataFrame after replacing missing values with column means:
      Income        Age        Edu
0  56.000000  22.000000  11.000000
1  58.000000  23.000000  13.000000
2  60.000000  29.142857  15.285714
3  62.000000  25.000000  14.000000
4  64.714286  27.000000  15.000000
5  69.000000  33.000000  16.000000
6  73.000000  36.000000  18.000000
7  75.000000  38.000000  20.000000

In [12]:
# Replace missing values with the median of each column
df_median_filled = df.fillna(df.median())
print("\nDataFrame after replacing missing values with column medians:")
print(df_median_filled)

DataFrame after replacing missing values with column medians:
   Income   Age   Edu
0    56.0  22.0  11.0
1    58.0  23.0  13.0
2    60.0  27.0  15.0
3    62.0  25.0  14.0
4    62.0  27.0  15.0
5    69.0  33.0  16.0
6    73.0  36.0  18.0
7    75.0  38.0  20.0

In [13]:
df

   Income   Age   Edu
0    56.0  22.0  11.0
1    58.0  23.0  13.0
2    60.0   NaN   NaN
3    62.0  25.0  14.0
4     NaN  27.0  15.0
5    69.0  33.0  16.0
6    73.0  36.0  18.0
7    75.0  38.0  20.0

In [14]:
# Using forward fill to replace missing values
df_ffill = df.fillna(method='ffill')
print("\nDataFrame after forward filling missing values:")
print(df_ffill)

DataFrame after forward filling missing values:
   Income   Age   Edu
0    56.0  22.0  11.0
1    58.0  23.0  13.0
2    60.0  23.0  13.0
3    62.0  25.0  14.0
4    62.0  27.0  15.0
5    69.0  33.0  16.0
6    73.0  36.0  18.0
7    75.0  38.0  20.0

<ipython-input-14-c58739c455d7>:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_ffill = df.fillna(method='ffill')

In [15]:
# Using backward fill to replace missing values
df_bfill = df.fillna(method='bfill')
print("\nDataFrame after backward filling missing values:")
print(df_bfill)

DataFrame after backward filling missing values:
   Income   Age   Edu
0    56.0  22.0  11.0
1    58.0  23.0  13.0
2    60.0  25.0  14.0
3    62.0  25.0  14.0
4    69.0  27.0  15.0
5    69.0  33.0  16.0
6    73.0  36.0  18.0
7    75.0  38.0  20.0

<ipython-input-15-23b670b79d9e>:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_bfill = df.fillna(method='bfill')

In [16]:
# Using interpolation to fill missing values
df_interpolated = df.interpolate()
print("\nDataFrame after interpolation of missing values:")
print(df_interpolated)

DataFrame after interpolation of missing values:
   Income   Age   Edu
0    56.0  22.0  11.0
1    58.0  23.0  13.0
2    60.0  24.0  13.5
3    62.0  25.0  14.0
4    65.5  27.0  15.0
5    69.0  33.0  16.0
6    73.0  36.0  18.0
7    75.0  38.0  20.0

In [18]:
# Prepare the formula for regression
# We'll predict column 'A' based on columns 'B' and 'C'
formula = 'Income ~ Age + Edu'
# Fit the regression model using only complete cases
model = smf.ols(formula, data=df.dropna()).fit()

In [19]:
# Predict missing values
# Create a new DataFrame with missing values only
missing_data = df[df['Income'].isnull()]

In [20]:
missing_data

   Income   Age   Edu
4     NaN  27.0  15.0

In [21]:
# Predict using the fitted model
predictions = model.predict(missing_data)

In [22]:
predictions

4    63.233034
dtype: float64

In [23]:
print("\nDataFrame after imputation:\n") # Imputation means estimating and filling the missing values in the dataset
df.loc[4, 'Income'] = predictions.values
print(df)

DataFrame after imputation:

      Income   Age   Edu
0  56.000000  22.0  11.0
1  58.000000  23.0  13.0
2  60.000000   NaN   NaN
3  62.000000  25.0  14.0
4  63.233034  27.0  15.0
5  69.000000  33.0  16.0
6  73.000000  36.0  18.0
7  75.000000  38.0  20.0

In [24]:
# Create a sample DataFrame with missing values
data = {
'Income Level': ['High', 'Low', np.nan, 'Low', 'Low', np.nan, 'High'],
'Age': [20, 30, 40, 50, 60, 70, 80]
}
df = pd.DataFrame(data)
df

  Income Level  Age
0         High   20
1          Low   30
2          NaN   40
3          Low   50
4          Low   60
5          NaN   70
6         High   80

In [25]:
# Detect missing values
missing_values = df['Income Level'].isnull()
print("Missing Values:\n", missing_values)

Missing Values:
 0    False
1    False
2     True
3    False
4    False
5     True
6    False
Name: Income Level, dtype: bool

In [26]:
# Count missing values
missing_count = df['Income Level'].isnull().sum()
print("\nMissing Value Count:", missing_count)

Missing Value Count: 2

In [27]:
# Calculate the mode of the 'Income Level' column
mode_category = df['Income Level'].mode()[0]

In [28]:
mode_category

'Low'

In [29]:
# Replace missing values with the mode
df['Income Level'] = df['Income Level'].fillna(mode_category)
print("\nData after imputation:\n", df)

Data after imputation:
   Income Level  Age
0         High   20
1          Low   30
2          Low   40
3          Low   50
4          Low   60
5          Low   70
6         High   80

# Dealing With Outliers

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

# Using Z-Score

In [ ]:
data = [10, 12, 12, 13, 12, 12, 100, 12, 14, 12, 12, 13]
mean = np.mean(data)
std_dev = np.std(data)

In [ ]:
mean

In [ ]:
std_dev

In [ ]:
# Detect outliers using Z-Score
threshold = 3
outliers_z_score = [x for x in data if abs((x - mean) / std_dev) > threshold]

In [ ]:
outliers_z_score

In [ ]:
# Visualization
plt.figure(figsize=(10, 5))
plt.plot(data, 'bo-', label='Data Points')
plt.axhline(y=mean + threshold * std_dev, color='r', linestyle='--',
label='Upper Threshold')
plt.axhline(y=mean - threshold * std_dev, color='r', linestyle='--',
label='Lower Threshold')
plt.title('Z-Score Method for Outlier Detection')
plt.xlabel('Index')
plt.ylabel('Values')
plt.legend()
plt.show()

# Using the IQR Method

In [ ]:
sample_data = np.array([1, 2, 2, 4, 5, 20])

In [ ]:
# Calculate IQR
q1 = np.percentile(sample_data, 25)
q3 = np.percentile(sample_data, 75)
iqr = q3 - q1
lower_bound = q1 - 1.5 * iqr
upper_bound = q3 + 1.5 * iqr

In [ ]:
# Detect outliers
outliers_iqr = sample_data[(sample_data < lower_bound) | (sample_data > upper_bound)]

In [ ]:
outliers_iqr

In [ ]:
plt.figure(figsize=(10, 5))
plt.boxplot(sample_data)
plt.axhline(y=lower_bound, color='r', linestyle='--', label='Lower Bound')
plt.axhline(y=upper_bound, color='r', linestyle='--', label='Upper Bound')
plt.title('IQR Method for Outlier Detection')
plt.xlabel('Values')
plt.show()