# Import Libraries

In [ ]:
import pandas as pd
import statsmodels.api as sm

# Create the data in the form of DataFrame

In [ ]:
data = {
    'Test_Score': [85, 90, 88, 92, 78, 82, 80, 76],
    'Study_Hours': [10, 12, 11, 13, 8, 9, 7, 6],
    'Gender': ['Male', 'Male', 'Male', 'Male', 'Female', 'Female', 'Female', 'Female']
}

# Create a DataFrame
df = pd.DataFrame(data)
df

   Test_Score  Study_Hours  Gender
0          85           10    Male
1          90           12    Male
2          88           11    Male
3          92           13    Male
4          78            8  Female
5          82            9  Female
6          80            7  Female
7          76            6  Female

# Convert the categorical variable 'Gender' into dummy variables

In [ ]:
df_dummies_Gender = pd.get_dummies(df['Gender'])
df_dummies_Gender

   Female   Male
0   False   True
1   False   True
2   False   True
3   False   True
4    True  False
5    True  False
6    True  False
7    True  False

# Convert the categorical variable 'Gender' into dummy variables and dropping the first dummy variable

In [ ]:
df_dummies_Male = pd.get_dummies(df['Gender'], drop_first=True)
df_dummies_Male

    Male
0   True
1   True
2   True
3   True
4  False
5  False
6  False
7  False

# Concatenate dummies to original Dataset

In [ ]:
df2 = pd.concat([df,df_dummies_Male], axis = 1)
df2

   Test_Score  Study_Hours  Gender   Male
0          85           10    Male   True
1          90           12    Male   True
2          88           11    Male   True
3          92           13    Male   True
4          78            8  Female  False
5          82            9  Female  False
6          80            7  Female  False
7          76            6  Female  False

# Drop the Gender column because we have created dummy variables for this column

In [ ]:
df2.drop(['Gender'], axis = 1, inplace = True)
df2

   Test_Score  Study_Hours   Male
0          85           10   True
1          90           12   True
2          88           11   True
3          92           13   True
4          78            8  False
5          82            9  False
6          80            7  False
7          76            6  False

# Using Multilinear Regression predict the test score using the independent variables

In [ ]:
X = df2[['Study_Hours', 'Male']]
X = sm.add_constant(X)  # Add a constant term for the intercept

X

   const  Study_Hours   Male
0    1.0           10   True
1    1.0           12   True
2    1.0           11   True
3    1.0           13   True
4    1.0            8  False
5    1.0            9  False
6    1.0            7  False
7    1.0            6  False

In [ ]:
# Define the dependent variable (Test_Score)
y = df['Test_Score']

# Perform Regression using Least Sqaure Method and print the model summary

In [ ]:
# Fit the regression model
model = sm.OLS(y, X.astype(float)).fit()

# Print the summary of the regression
print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:             Test_Score   R-squared:                       0.963
Model:                            OLS   Adj. R-squared:                  0.948
Method:                 Least Squares   F-statistic:                     65.37
Date:                Fri, 02 May 2025   Prob (F-statistic):           0.000260
Time:                        16:53:00   Log-Likelihood:                -11.699
No. Observations:                   8   AIC:                             29.40
Df Residuals:                       5   BIC:                             29.64
Df Model:                           2
Covariance Type:            nonrobust
===============================================================================
                  coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------
const          64.3750      3.202     20.106      0.000      56.144      72.606
Study_Hours     1.9500      0.418      4.668      0.005       0.876       3.024
Male            1.9500      1.914      1.019      0.355      -2.971       6.871
==============================================================================
Omnibus:                        1.652   Durbin-Watson:                   2.123
Prob(Omnibus):                  0.438   Jarque-Bera (JB):                0.025
Skew:                          -0.054   Prob(JB):                        0.988
Kurtosis:                       3.249   Cond. No.                         75.8
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

/usr/local/lib/python3.11/dist-packages/scipy/stats/_axis_nan_policy.py:430: UserWarning: `kurtosistest` p-value may be inaccurate with fewer than 20 observations; only n=8 observations were given.
  return hypotest_fun_in(*args, **kwds)